---
- name: Get container config
  shell: pvesh get /nodes/{{ proxmox_lxc_node }}/lxc/{{ proxmox_lxc_vmid }}/config --output-format json
  register: container_config_cmd
  delegate_to: "{{ proxmox_api_host }}"

- name: Configure container memory and CPU
  shell: >
    pvesh set /nodes/{{ proxmox_lxc_node }}/lxc/{{ proxmox_lxc_vmid }}/config \
      --memory "{{ proxmox_lxc_memory }}" \
      --swap "{{ proxmox_lxc_swap }}" \
      --cores "{{ proxmox_lxc_cores }}"
  when: >
    container_config.memory != proxmox_lxc_memory or
    container_config.swap != proxmox_lxc_swap or
    container_config.cores != proxmox_lxc_cores
  delegate_to: "{{ proxmox_api_host }}"

# TODO: remove networks that are not in proxmox_lxc_net_interfaces
# FIXME: firewall is not getting parsed as a number
- name: Configure network
  shell: "pvesh set /nodes/{{ proxmox_lxc_node }}/lxc/{{ proxmox_lxc_vmid }}/config --net{{ index }} 'name=eth{{ index }},{{ config }}'"
  loop: "{{ proxmox_lxc_net_interfaces | dict2items }}"
  loop_control:
    index_var: index
  vars:
    config: "{{ item.value.keys() | zip(item.value.values()) | map('join', '=') | join(',') }}"
  delegate_to: "{{ proxmox_api_host }}"

- name: Configure mounts
  shell: >
    pvesh set /nodes/{{ proxmox_lxc_node }}/lxc/{{ proxmox_lxc_vmid }}/config \
      --{{ item.key }} 'volume={{ item.value.storage }}:{{ item.value.size }},mp={{ item.value.mp}},backup={{ item.value.backup }}'
  loop: "{{ proxmox_lxc_mounts | dict2items }}"
  when: item.key not in container_config
  delegate_to: "{{ proxmox_api_host }}"
