---
- name: Configure cpu
  delegate_to: "{{ proxmox_api_host }}"
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_lxc_vmid }}.conf"
    regexp: "^cores: "
    line: "cores: {{ proxmox_lxc_cores }}"
    state: present

- name: Configure memory
  delegate_to: "{{ proxmox_api_host }}"
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_lxc_vmid }}.conf"
    regexp: "^memory: "
    line: "memory: {{ proxmox_lxc_memory }}"
    state: present

- name: Configure swap
  delegate_to: "{{ proxmox_api_host }}"
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_lxc_vmid }}.conf"
    regexp: "^swap: "
    line: "swap: {{ proxmox_lxc_swap }}"
    state: present

- name: Configure features
  delegate_to: "{{ proxmox_api_host }}"
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_lxc_vmid }}.conf"
    regexp: "^features: "
    line: "features: {{ proxmox_lxc_features }}"
    state: present

- name: Configure hostname
  delegate_to: "{{ proxmox_api_host }}"
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_lxc_vmid }}.conf"
    regexp: "^hostname: "
    line: "hostname: {{ proxmox_lxc_hostname }}"
    state: present

- name: Configure volumes
  delegate_to: "{{ proxmox_api_host }}"
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_lxc_vmid }}.conf"
    regexp: "^mp{{ index }}: "
    line: "mp{{ index }}: {{ item.storage }}:{{ filename }},backup={{ item.backup | default(0) }},mp={{ item.mp }},size={{ item.size }}G"
    state: present
  loop: "{{ proxmox_lxc_mounts }}"
  loop_control:
    index_var: index
  vars:
    filename: "{{ item.filename | default(default_filename) }}"
    default_filename: "{{ (format == 'raw') | ternary('vm', 'subvol') }}-{{ proxmox_lxc_vmid }}-mp-{{ index }}"
    format: "{{ item.format | default('raw') }}"

- name: Configure network
  delegate_to: "{{ proxmox_api_host }}"
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_lxc_vmid }}.conf"
    regexp: "^net{{ index }}: "
    line: "net{{ index }}: name=eth{{ index }},{{ item.keys() | zip(item.values()) | map('join', '=') | join(',') }}"
    state: present
  loop: "{{ proxmox_lxc_net_interfaces }}"
  loop_control:
    index_var: index
