---
# FIXME: ATM needs to run after network is added, otherwise DNS resolution fails.
#   The network should be hotpluggable.
- name: Start container
  shell: >
    pvesh create /nodes/{{ proxmox_lxc_node }}/lxc/{{ proxmox_lxc_vmid }}/status/start
  when: create_container_cmd.changed
  delegate_to: "{{ proxmox_api_host }}"
  retries: 1
  delay: 5
  listen: container created

- name: Proxmox LXC post install
  shell: "{{ proxmox_lxc_postinstall }}"
  delegate_to: "{{ proxmox_api_host }}"
  listen: container created
  # wait for the VM to come online
  retries: 5
  delay: 3
  register: result
  until: result.rc == 0 and result.stderr == ''
  when: proxmox_lxc_postinstall

- name: Scan for SSH host keys
  shell:
    cmd: "ssh-keyscan {{ ansible_host }} 2>/dev/null"
  changed_when: false
  retries: 5
  delay: 3
  register: ssh_scan
  until: ssh_scan.rc == 0 and ssh_scan.stdout != ''
  delegate_to: "{{ proxmox_api_host }}"
  listen: container created

- name: Update known_hosts
  local_action:
    module: known_hosts
    key: "{{ item }}"
    name: "{{ item | split(' ') | first }}"
  loop: "{{ ssh_scan.stdout_lines }}"
  listen: container created
